// Copyright 2025 @polkadot-live/polkadot-live-app authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

import { faFileExport, faFileImport } from '@fortawesome/free-solid-svg-icons';
import type { SettingItem, SettingKey } from '@polkadot-live/types/settings';

export const getDefaultSettings = () =>
  new Map<SettingKey, boolean>([
    ['setting:automatic-subscriptions', false],
    ['setting:collapse-side-nav', false],
    ['setting:dark-mode', true],
    ['setting:docked-window', false],
    ['setting:enable-polkassembly', true],
    ['setting:export-data', false],
    ['setting:hide-dock-icon', false],
    ['setting:import-data', false],
    ['setting:keep-outdated-events', true],
    ['setting:show-all-workspaces', false],
    ['setting:show-debugging-subscriptions', false],
    ['setting:silence-extrinsic-notifications', false],
    ['setting:silence-os-notifications', false],
  ]);

export const SettingsList: SettingItem[] = [
  {
    category: 'General',
    enabled: true,
    helpKey: 'help:settings:dockedWindow',
    key: 'setting:docked-window',
    settingType: 'switch',
    title: 'Docked Window',
    platforms: ['darwin', 'win32'],
  },
  {
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:showOnAllWorkspaces',
    key: 'setting:show-all-workspaces',
    settingType: 'switch',
    title: 'Show On All Workspaces',
    platforms: ['darwin', 'linux'],
  },
  {
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:silenceOsNotifications',
    key: 'setting:silence-os-notifications',
    settingType: 'switch',
    title: 'Silence OS Notifications',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:enablePolkassembly',
    key: 'setting:enable-polkassembly',
    settingType: 'switch',
    title: 'Enable Polkassembly Data',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:hideDockIcon',
    key: 'setting:hide-dock-icon',
    settingType: 'switch',
    title: 'Hide Dock Icon',
    platforms: ['darwin'],
  },
  {
    category: 'Subscriptions',
    enabled: false,
    helpKey: 'help:settings:showDebuggingSubscriptions',
    key: 'setting:show-debugging-subscriptions',
    settingType: 'switch',
    title: 'Show Debugging Subscriptions',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'Subscriptions',
    enabled: false,
    helpKey: 'help:settings:enableAutomaticSubscriptions',
    key: 'setting:automatic-subscriptions',
    settingType: 'switch',
    title: 'Enable Automatic Subscriptions',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'Subscriptions',
    enabled: true,
    helpKey: 'help:settings:keepOutdatedEvents',
    key: 'setting:keep-outdated-events',
    settingType: 'switch',
    title: 'Keep Outdated Events',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'Extrinsics',
    enabled: false,
    helpKey: 'help:settings:silenceExtrinsicsOsNotifications',
    key: 'setting:silence-extrinsic-notifications',
    settingType: 'switch',
    title: 'Silence OS Notifications for Extrinsics',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'Backup',
    buttonIcon: faFileImport,
    buttonText: 'Import',
    enabled: true,
    helpKey: 'help:settings:importData',
    key: 'setting:import-data',
    settingType: 'button',
    title: 'Import Data',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
  {
    category: 'Backup',
    buttonIcon: faFileExport,
    buttonText: 'Export',
    enabled: true,
    helpKey: 'help:settings:exportData',
    key: 'setting:export-data',
    settingType: 'button',
    title: 'Export Data',
    platforms: ['chrome', 'darwin', 'win32', 'linux'],
  },
];
