// Copyright 2024 @polkadot-live/polkadot-live-app authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

import { faFileExport, faFileImport } from '@fortawesome/free-solid-svg-icons';
import type { SettingItem } from '@polkadot-live/types/settings';

export const SettingsList: SettingItem[] = [
  {
    action: 'settings:execute:dockedWindow',
    category: 'General',
    enabled: true,
    helpKey: 'help:settings:dockedWindow',
    settingType: 'switch',
    title: 'Docked Window',
    platforms: ['darwin', 'win32'],
  },
  {
    action: 'settings:execute:showOnAllWorkspaces',
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:showOnAllWorkspaces',
    settingType: 'switch',
    title: 'Show On All Workspaces',
    platforms: ['darwin', 'linux'],
  },
  {
    action: 'settings:execute:silenceOsNotifications',
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:silenceOsNotifications',
    settingType: 'switch',
    title: 'Silence OS Notifications',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:enablePolkassembly',
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:enablePolkassembly',
    settingType: 'switch',
    title: 'Enable Polkassembly Data',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:hideDockIcon',
    category: 'General',
    enabled: false,
    helpKey: 'help:settings:hideDockIcon',
    settingType: 'switch',
    title: 'Hide Dock Icon',
    platforms: ['darwin'],
  },
  {
    action: 'settings:execute:showDebuggingSubscriptions',
    category: 'Subscriptions',
    enabled: false,
    helpKey: 'help:settings:showDebuggingSubscriptions',
    settingType: 'switch',
    title: 'Show Debugging Subscriptions',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:enableAutomaticSubscriptions',
    category: 'Subscriptions',
    enabled: false,
    helpKey: 'help:settings:enableAutomaticSubscriptions',
    settingType: 'switch',
    title: 'Enable Automatic Subscriptions',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:keepOutdatedEvents',
    category: 'Subscriptions',
    enabled: true,
    helpKey: 'help:settings:keepOutdatedEvents',
    settingType: 'switch',
    title: 'Keep Outdated Events',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:silenceExtrinsicsOsNotifications',
    category: 'Extrinsics',
    enabled: false,
    helpKey: 'help:settings:silenceExtrinsicsOsNotifications',
    settingType: 'switch',
    title: 'Silence OS Notifications for Extrinsics',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:importData',
    category: 'Backup',
    buttonIcon: faFileImport,
    buttonText: 'Import',
    enabled: true,
    helpKey: 'help:settings:importData',
    settingType: 'button',
    title: 'Import Data',
    platforms: ['darwin', 'win32', 'linux'],
  },
  {
    action: 'settings:execute:exportData',
    category: 'Backup',
    buttonIcon: faFileExport,
    buttonText: 'Export',
    enabled: true,
    helpKey: 'help:settings:exportData',
    settingType: 'button',
    title: 'Export Data',
    platforms: ['darwin', 'win32', 'linux'],
  },
];
