// Copyright 2025 @polkadot-live/polkadot-live-app authors & contributors
// SPDX-License-Identifier: GPL-3.0-only

import type { SubscriptionTask } from '@polkadot-live/types/subscriptions';

/**
 * @name accountTasks
 * @summary A list of all possible tasks an account can subscribe to. The `SubscriptionTask`
 * type acts as the bridge between the main and renderer processes for synching and handling
 * subscriptions.
 *
 * By default, all subscription tasks are marked with status `disable`. A task is marked
 * as `enable` when it is toggled on the frontend, or fetched from the store as an
 * active task on app initialization.
 */
export const accountTasks: SubscriptionTask[] = [
  // Polkadot
  {
    action: 'subscribe:account:balance:free',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:transfers',
    label: 'Free',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:frozen',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:frozen',
    label: 'Frozen',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:reserved',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:reserved',
    label: 'Reserved',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:spendable',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:spendable',
    label: 'Spendable',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:rewards',
    apiCallAsString: 'api.query.system.account',
    category: 'Nomination Pools',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:rewards',
    label: 'Unclaimed Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:state',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:state',
    label: 'Pool State Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:renamed',
    apiCallAsString: 'api.query.nominationPools.metadata',
    category: 'Nomination Pools',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:name',
    label: 'Pool Name Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:roles',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:roles',
    label: 'Roles Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:commission',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:pendingPayouts',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:payouts',
    label: 'Era Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:exposure',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:exposure',
    label: 'Exposure Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:commission',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:nominations',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Polkadot',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:nominations',
    label: 'Nominations Changed',
    status: 'disable',
  },
  // Kusama
  {
    action: 'subscribe:account:balance:free',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:transfers',
    label: 'Free',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:frozen',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:frozen',
    label: 'Frozen',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:reserved',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:reserved',
    label: 'Reserved',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:spendable',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:spendable',
    label: 'Spendable',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:rewards',
    apiCallAsString: 'api.query.system.account',
    category: 'Nomination Pools',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:rewards',
    label: 'Unclaimed Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:state',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:state',
    label: 'State Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:renamed',
    apiCallAsString: 'api.query.nominationPools.metadata',
    category: 'Nomination Pools',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:name',
    label: 'Pool Name Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:roles',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:roles',
    label: 'Roles Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:commission',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:pendingPayouts',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:payouts',
    label: 'Era Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:exposure',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:exposure',
    label: 'Exposure Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:commission',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:nominations',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Kusama',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:nominations',
    label: 'Nominations Changed',
    status: 'disable',
  },
  // Polkadot Asset Hub
  {
    action: 'subscribe:account:balance:free',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:transfers',
    label: 'Free',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:frozen',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:frozen',
    label: 'Frozen',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:reserved',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:reserved',
    label: 'Reserved',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:spendable',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Polkadot Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:spendable',
    label: 'Spendable',
    status: 'disable',
  },
  // Westend
  {
    action: 'subscribe:account:balance:free',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:transfers',
    label: 'Free',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:frozen',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:frozen',
    label: 'Frozen',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:reserved',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:reserved',
    label: 'Reserved',
    status: 'disable',
  },
  {
    action: 'subscribe:account:balance:spendable',
    apiCallAsString: 'api.query.system.account',
    category: 'Balances',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:balances:spendable',
    label: 'Spendable',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:rewards',
    apiCallAsString: 'api.query.system.account',
    category: 'Nomination Pools',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:rewards',
    label: 'Unclaimed Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:state',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:state',
    label: 'State Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:renamed',
    apiCallAsString: 'api.query.nominationPools.metadata',
    category: 'Nomination Pools',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:name',
    label: 'Pool Name Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:roles',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:roles',
    label: 'Roles Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominationPools:commission',
    apiCallAsString: 'api.query.nominationPools.bondedPools',
    category: 'Nomination Pools',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominationPools:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:pendingPayouts',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:payouts',
    label: 'Era Rewards',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:exposure',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:exposure',
    label: 'Exposure Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:commission',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:commission',
    label: 'Commission Changed',
    status: 'disable',
  },
  {
    action: 'subscribe:account:nominating:nominations',
    apiCallAsString: 'api.query.staking.activeEra',
    category: 'Nominating',
    chainId: 'Westend Asset Hub',
    enableOsNotifications: true,
    helpKey: 'help:subscription:nominating:nominations',
    label: 'Nominations Changed',
    status: 'disable',
  },
];
